- name: Install Zsh
  pacman:
    name: zsh
    state: present

- name: Change shell to Zsh
  command: chsh -s /bin/zsh 

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: Download .zshrc from GitHub
  shell: curl -LO https://github.com/ml3m/.dotfiles/raw/main/.zshrc

- name: Move .zshrc to home directory
  shell: mv .zshrc ~/
